$(document).ready(function(){
    $("#sun").mouseenter(function(){
        $("#suntxt").show(4000);
        $('[data-toggle="popover"]').popover();
    });
    $("#sun").mouseleave(function(){       
        $("#suntxt").hide(2000);
    });
    $("#mercury").mouseenter(function(){
        $("#mertxt").show(4000);
        $('[data-toggle="popover"]').popover();
    });
    $("#mercury").mouseleave(function(){
        $("#mertxt").hide(2000);
    });
    $("#venus").mouseenter(function(){
        $("#ventxt").show(4000);
        $('[data-toggle="popover"]').popover();
    });
    $("#venus").mouseleave(function(){
        $("#ventxt").hide(2000);
    });
    $("#earth").mouseenter(function(){
        $("#earthtxt").show(4000);
        $('[data-toggle="popover"]').popover();
    });
    $("#earth").mouseleave(function(){
        $("#earthtxt").hide(2000);
    });
    $("#mars").mouseenter(function(){
        $("#marstxt").show(4000);
        $('[data-toggle="popover"]').popover();
    });
    $("#mars").mouseleave(function(){
        $("#marstxt").hide(2000);
    });
    $("#jupiter").mouseenter(function(){
        $("#jupitertxt").show(4000);
        $('[data-toggle="popover"]').popover();
    });
    $("#jupiter").mouseleave(function(){
        $("#jupitertxt").hide(2000);
    });
    $("#saturn").mouseenter(function(){
        $("#saturntxt").show(4000);
        $('[data-toggle="popover"]').popover();
    });
    $("#saturn").mouseleave(function(){
        $("#saturntxt").hide(2000);
    });
    $("#uranus").mouseenter(function(){
        $("#uranustxt").show(4000);
        $('[data-toggle="popover"]').popover();
    });
    $("#uranus").mouseleave(function(){
        $("#uranustxt").hide(2000);
    });
    $("#neptune").mouseenter(function(){
        $("#neptxt").show(4000);
        $('[data-toggle="popover"]').popover();
    });
    $("#neptune").mouseleave(function(){
        $("#neptxt").hide(2000);
    });
});
